name: easy_use_camera
description: Easy to use camera for all platform.
version: 0.0.15
repository: https://github.com/amirsheibani/easy_use_camera
homepage: https://github.com/amirsheibani/easy_use_camera#readme


environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.11.0+2
  flutter_svg: ^2.0.9
  camera_platform_interface: ^2.6.0
  image: ^4.1.3
  flutter_image_compress: ^2.1.0
  video_player: ^2.8.1
  video_player_web: ^2.1.2
  chewie: ^1.7.4
  universal_html: any
  ffmpeg_wasm: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

