name: easy_use_camera
description: Handler camera for all platform.
version: 0.0.5
homepage: https://github.com/amirsheibani/easy_use_camera

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.10.5+5
  flutter_svg: ^2.0.9
  camera_platform_interface: ^2.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

